[platformio]
src_dir = main

[env:esp32dev]
platform            = espressif32
board               = esp32dev
framework           = espidf
monitor_speed       = 115200
board_build.partitions = partitions.csv
build_flags         = -O2
board_upload.flash_size = 4MB
